### ISSUE TITLE
Probably missing dependencies causing fails in yarn pnp context

### ISSUE THREAD

**Issue by kubijo** [davipon/esbuild-plugin-pino#73]
I had to add the following for this module to work in a Yarn PnP context:

```yaml .yarnrc.yml
packageExtensions:
  "esbuild-plugin-pino@*":
    dependencies:
      "pino": "*"
      "pino-pretty": "*"
      "thread-stream": "*"
```

**Comment by viceice** [comment]
I only need this to fix:
```yml
packageExtensions:
  esbuild-plugin-pino@*:
    dependencies:
      'thread-stream': '*'
```
